# Generated by Django 5.1 on 2026-01-17 14:49

import django.contrib.auth.validators
import django.db.models.deletion
import django_rest_passwordreset.tokens
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-dt',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Список позиций заказа'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметр продукта', 'verbose_name_plural': 'Список параметров продукта'},
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_item',
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время генерации токена'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='key',
            field=models.CharField(db_index=True, default=django_rest_passwordreset.tokens.RandomStringTokenGenerator.generate_token, max_length=64, unique=True, verbose_name='Ключевой токен'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_email_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, связанный с этим токеном'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('basket', 'Корзина'), ('new', 'Новый'), ('confirmed', 'Подтверждён'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменён')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Статус получения заказов'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Такой пользователь уже существует.'}, help_text='Требуется. Не больше 150 символов. Буквы, цифры и символы @/./+/-/_ разрешены.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product_info'), name='unique_order_item'),
        ),
    ]
