# Generated by Django 5.1 on 2026-01-21 15:55

import django_rest_passwordreset.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='key',
            field=models.CharField(db_index=True, default=django_rest_passwordreset.tokens.RandomStringTokenGenerator.generate_token, max_length=64, unique=True, verbose_name='Ключевой токен'),
        ),
    ]
