# Generated by Django 5.1 on 2026-01-25 12:13

import django.db.models.deletion
import django_rest_passwordreset.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_productinfo_updated_at_alter_confirmemailtoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='key',
            field=models.CharField(db_index=True, default=django_rest_passwordreset.tokens.RandomStringTokenGenerator.generate_token, max_length=64, unique=True, verbose_name='Ключевой токен'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.product')),
            ],
        ),
    ]
