# Generated by Django 5.1 on 2026-01-25 12:37

import django_rest_passwordreset.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_avatar_alter_confirmemailtoken_key_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='key',
            field=models.CharField(db_index=True, default=django_rest_passwordreset.tokens.RandomStringTokenGenerator.generate_token, max_length=64, unique=True, verbose_name='Ключевой токен'),
        ),
    ]
