# Generated by Django 5.1 on 2026-01-25 13:47

import django_rest_passwordreset.tokens
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_confirmemailtoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='key',
            field=models.CharField(db_index=True, default=django_rest_passwordreset.tokens.RandomStringTokenGenerator.generate_token, max_length=64, unique=True, verbose_name='Ключевой токен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
